#!/bin/sh

REPOSITORY_NAME="$0"
BIRTHDAY="$1"

read -p "Github Username: " USERNAME

if [ -z "$USERNAME" ]
then
  exit 1
fi

if [ ! -n "$REPOSITORY_NAME" ]
then
  echo "REPOSITORY_NAME IS NULL"
  exit 2
fi

if [ ! -n "$BIRTHDAY" ]
then
  echo "BIRTHDAY IS NULL"
  exit 3
fi

mkdir $REPOSITORY_NAME
cd $REPOSITORY_NAME
git init
echo "**$BIRTHDAY** - Generated by https://github.com/Supertinypeanut/birthday-script" > README.md
git add .
GIT_AUTHOR_DATE="$BIRTHDAY T18:00:00" GIT_COMMITTER_DATE="$BIRTHDAY T18:00:00" git commit -m "init:I was born on $BIRTHDAY"
git remote add origin https://github.com/$USERNAME/$REPOSITORY_NAME.git
git push -u origin master -f
cd ..
rm -rf $REPOSITORY_NAME

echo
echo Cool, check your profile now: https://github.com/$USERNAME
